### ISSUE TITLE
Provide an example of scoring based on path length

### ISSUE THREAD

**Issue by bachmanm** [graphaware/neo4j-reco#10]

**Comment by bachmanm** [comment]
Hey @ikwattro could you pls change the example to give negative points? I.e. the longer the path, the lower the score, I think that would make more sense. Close this one pls when done, thx!

**Comment by ikwattro** [comment]
@bachmanm does it looks ok for you ?

https://github.com/graphaware/neo4j-reco/commit/2b38e4af75436072da53ed289dbf8d7dc71ce9a1#diff-b0d9f7a01f484e16ac07f9dc3bcf221aR48
