### ISSUE TITLE
How to implement k-Nearest Neighbour similarity

### ISSUE THREAD

**Issue by tolomaus** [graphaware/neo4j-reco#11]
Hi,

I have been playing with this awesome recommenation engine (see my [recommendations](https://github.com/tolomaus/recommendations) github repo) to calculate recommendations with a collaboration-based and a content-based strategy. 

Now I'm wondering how I could implement a k-Nearest Neighbour similarity with the engine, as explained in [this article](http://gist.neo4j.org/?8173017).

**Comment by bachmanm** [comment]
This is something I would personally code as a "background" job using the GraphAware Framework's [Timer-Driven](https://github.com/graphaware/neo4j-framework/tree/master/runtime#building-a-timer-driven-graphaware-runtime-module) functionality. A reference implementation of that is our [NodeRank](https://github.com/graphaware/neo4j-noderank/) module. We may get around to implementing it at some point, but a pull request from you will be welcome of you feel like it! Cheers!

**Comment by tolomaus** [comment]
Hi Michal,

Indeed we could calculate the similarity in the background with some "NodeRankBykNN" module and then use this similarity index in a recommendation module.

Thanks for the pointer. If I get around to implement it I will definitely send it as a PR.

Niek.
