### ISSUE TITLE
FriendsComputingEngine wasn't found on the classpath

### ISSUE THREAD

**Issue by sreejithc321** [graphaware/neo4j-reco#16]
I am getting this error : 

ERROR c.g.r.n.m.RecommendationModuleBootstrapper - Engine com.graphaware.reco.integration.FriendsComputingEngine wasn't found on the classpath. Will not pre-compute recommendations

How to solve this ?

**Comment by bachmanm** [comment]
Well, did you build a `FriendsComputingEngine`? :)

**Comment by sreejithc321** [comment]
Hi Bachmanm, 

I have created a java file (https://github.com/graphaware/neo4j-reco#putting-it-all-together) and placed the following files to plugin directory :

FriendsComputingEngine.java  
graphaware-reco-2.3.1.36.9.jar  
graphaware-server-community-all-2.3.1.36.jar

**Comment by bachmanm** [comment]
The `FriendsComputingEngine` you've built is surely a part of a project, which (if it is a Maven project) should produce a .jar file when you `mvn package`. Please place that .jar into plugins, rather than just a single Java class

**Comment by sreejithc321** [comment]
Hi Michal,

I am Sreejith and I recently attended Neo4j workshop by Luanne.

I just started exploring Neo4j-reco and going through this link
https://github.com/graphaware/neo4j-reco.

I have created a java file (
https://github.com/graphaware/neo4j-reco#putting-it-all-together) and
placed the following files to plugin directory :

FriendsComputingEngine.java
graphaware-reco-2.3.1.36.9.jar
graphaware-server-community-all-2.3.1.36.jar

But while restarting neo4j server I am getting these errors.

c.g.r.n.m.RecommendationModuleBootstrapper - Engine
com.graphaware.reco.integration.FriendsComputingEngine wasn't found on the
classpath. Will not pre-compute recommendations
java.lang.ClassNotFoundException:
com.graphaware.reco.integration.FriendsComputingEngine at
java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_91] at
java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_91] at
java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_91]
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
~[na:1.7.0_91] at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
~[na:1.7.0_91] at
sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
~[na:1.7.0_91] at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
~[na:1.7.0_91]

Can you please tell me why this issue is occurring and how to solve this ?

NB : I am Python guy and novice in Java :)

Thanks
Sreejith

**Comment by sreejithc321** [comment]
I ran  mvn package on the sorce code : https://github.com/graphaware/neo4j-reco

and get following jar files

graphaware-recommendation-engine-2.3.1.36.10-SNAPSHOT.jar  
recommendation-engine-2.3.1.36.10-SNAPSHOT-javadoc.jar
recommendation-engine-2.3.1.36.10-SNAPSHOT-sources.jar
generated-sources  recommendation-engine-2.3.1.36.10-SNAPSHOT.jar  


shall I add all those to plugin folder ?
