### ISSUE TITLE
Wrong graphaware algorithm dependency version

### ISSUE THREAD

**Issue by mihairaulea** [graphaware/neo4j-reco#23]
The dependency

<dependency>
            <groupId>com.graphaware.neo4j</groupId>
            <version>2.3.1.37.5-SNAPSHOT</version>
            <artifactId>algorithms</artifactId>
            <scope>test</scope>
        </dependency>

can not be found in the repository.

it should be just 
<version>2.3.1.37.5</version> (this works) 
OR
<version>2.3.1.37-SNAPSHOT</version> (for whatever reason, this does not work for me)

**Comment by bachmanm** [comment]
this should be ok now, sorry about that
