### ISSUE TITLE
New features request - SomethingWithSomethingInCommon and Dithering

### ISSUE THREAD

**Issue by f2net** [graphaware/neo4j-reco#3]
I think 2 features would be useful:
1) A recommendationEngine to find SomethingWithSomethingInCommon (for example other users who like films in the same category of films I like)
2) A dithering system to be run by the context at the end of the computation to "shuffle" the results (with a logic).

What do you think?

Thank you,
Matteo

**Comment by bachmanm** [comment]
I agree! On the backlog...

**Comment by omarlarus** [comment]
Hi, 
the enhancements of the neo4j-reco module are not in plan right now, but if anyone would like to contribute is welcome.
