### ISSUE TITLE
Weight discovery

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-reco#32]
Is there anyway you could weight (set importance) on the discovery strategies in order to calculate the total score?

Say I got three discovery strategies A, B and C. I want A to be 3 times more important than B. And C barley important at all. 
Total score = 3*A + B + 0.2*C

**Comment by ikwattro** [comment]
Well, You can add your weight configuration in the `Config` before running the engine. Then use it from the Config when overriding the `getScore` method. btw this is the java implementation, shouldn't this issue go to reco4php ?

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
Yes, You are correct. I was posing the issue in the wrong repo. But I found that your answer still applies.
