### ISSUE TITLE
Large sample data for Friend recommendation engine

### ISSUE THREAD

**Issue by mohammadMahdavi** [graphaware/neo4j-reco#34]
Did you have some sample data for your Friend recommendation engine that explain in read me?
Thanks.

**Comment by ikwattro** [comment]
Hi, 

Yes if you look at the tests you see that it load a fixtures file : 

https://github.com/graphaware/neo4j-reco/blob/master/src/test/resources/demo-data.cyp

If you are looking for a larger dataset, we do not provide such.
