### ISSUE TITLE
Assertion Error while running tests

### ISSUE THREAD

**Issue by Habush** [graphaware/neo4j-reco#35]
I tried to run the test methods in the [`ModuleIntegrationTest` ](https://github.com/graphaware/neo4j-reco/blob/master/src/test/java/com/graphaware/reco/integration/ModuleIntegrationTest.java ) test class. However, the tests fail with the following errors:

> java.lang.AssertionError: 
> Expected :2
> Actual   :0

That is, there are no recommendations being generated by the recommendation engine. What could be the cause of this? How can I resolve this?

**Comment by omarlarus** [comment]
Hi @Habush !
Do you run the "**mvn clean test**" command? Or do you run the test class using an IDE?

Thanks,
Omar

**Comment by Habush** [comment]
I am running the test using an IDE, Intellij IDEA to be specific.

**Comment by omarlarus** [comment]
@Habush can you paste the error log of maven, please?

**Comment by Habush** [comment]
Here you go:

> Running com.stavimer.ModuleIntegrationTest
> 2017-06-09 15:36:09.822+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware R
> 2017-06-09 15:36:18.212+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware R
> 2017-06-09 15:36:20.153+0000 INFO  [c.g.r.b.RuntimeKernelExtension] GraphAware R
> Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 19.632 sec <<< F
> shouldRecommendRealTime(com.stavimer.ModuleIntegrationTest)  Time elapsed: 13.02
> **java.lang.AssertionError: expected:<2> but was:<0>**
>         at org.junit.Assert.fail(Assert.java:88)
>         at org.junit.Assert.failNotEquals(Assert.java:834)
>         at org.junit.Assert.assertEquals(Assert.java:645)
>         at org.junit.Assert.assertEquals(Assert.java:631)
>         at com.stavimer.ModuleIntegrationTest.shouldRecommendRealTime(ModuleInte
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
>         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
>         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.ja
>         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>         at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
>         at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
>         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
>         at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
>         at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
>         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
> 
> shouldRecommendWithLittleTime(com.stavimer.ModuleIntegrationTest)  Time elapsed:
> **java.lang.AssertionError: expected:<2> but was:<0>**
>         at org.junit.Assert.fail(Assert.java:88)
>         at org.junit.Assert.failNotEquals(Assert.java:834)
>         at org.junit.Assert.assertEquals(Assert.java:645)
>         at org.junit.Assert.assertEquals(Assert.java:631)
>         at com.stavimer.ModuleIntegrationTest.shouldRecommendWithLittleTime(Modu
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
>         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
>         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.ja
>         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>         at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
>         at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
>         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
>         at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
>         at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
>         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
> 
> shouldRecommendPreComputed(com.stavimer.ModuleIntegrationTest)  Time elapsed: 4.
> **java.lang.AssertionError: expected:<2> but was:<0>**
>         at org.junit.Assert.fail(Assert.java:88)
>         at org.junit.Assert.failNotEquals(Assert.java:834)
>         at org.junit.Assert.assertEquals(Assert.java:645)
>         at org.junit.Assert.assertEquals(Assert.java:631)
>         at com.stavimer.ModuleIntegrationTest.shouldRecommendPreComputed(ModuleI
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
>         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
>         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.ja
>         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
>         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
>         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
>         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
>         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
>         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
>         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>         at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
>         at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
>         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
>         at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
>         at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
>         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
> 
> 
> Results :
> 
> **Failed tests:   shouldRecommendRealTime(com.stavimer.ModuleIntegrationTest): exp
>   shouldRecommendWithLittleTime(com.stavimer.ModuleIntegrationTest): expected:<2
>   shouldRecommendPreComputed(com.stavimer.ModuleIntegrationTest): expected:<2> b**
> 
> Tests run: 3, Failures: 3, Errors: 0, Skipped: 0

**Comment by Habush** [comment]
I have found the cause of the error. I was assigning the wrong label by a mistake and after fixing that it is works. But thank you for taking the time to reply to my comments.
